create user's group with custom gid before creating the user
The README.md shows an example of hard coding a UID but that functionality isn't
in the module right now. Pull request #14 has it so I merged it and resolved the
merge conflict.

Specifying the GID is also a nice feature, also included in pull request #14 but
if you do that, you need go create the group for the user (with the specified
GID) before you create the user. Puppet does autorequire the group for the user,
but just selects the next GID available, you need to manually create the group
if you want a custom GID. See error below for what happens if you try to create
a user with a custom UID and GID:

```
Error: Could not create user example: Execution of '/sbin/useradd -g 66666 -d /home/example -p * -u 66666 -m example' returned 6: useradd: group '66666' does not exist
Error: /Stage[main]/Profiles::Base/Accounts::Account[@herp]/Accounts::Account[example]/User[example]/ensure: change from absent to present failed: Could not create user example: Execution of '/sbin/useradd -g 66666 -d /home/example -p * -u 66666 -m example' returned 6: useradd: group '66666' does not exist
```